url: https://medpaleo.github.io
baseurl: /

# Site settings
title: MedPaleo
email: dnietolugilde@gmail.com
description: "Medpaleo is a research team that combine paleoecology, neoecology, phylogenetics, and ecoinformatics."


# Team names, titles and social links
people:
- name: Francisca Alba S치nchez
  pic: "img/team/falba.jpg"
  position: Professor
  institution: Universidad de Granada
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Julio Pe침as de Giles
  pic: "img/team/jpenas.jpg"
  position: Professor
  institution: Universidad de Granada
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diego Nieto Lugilde
  pic: "img/team/dnieto.jpg"
  position: Professor
  institution: Universidad de C칩rdoba
  social:
    - title: twitter
      url: #
    - title: github
      url: https://github.com/dinilu
    - title: google
      url: https://scholar.google.com/citations?user=JX3AT7EAAAAJ&hl=en
    - title: user
      url: https://dnietolugilde.com/

- name: Daniel Abel Schaad
  pic: "img/team/dabel.jpg"
  position: Postdoc researcher
  institution: Universidad de Granada
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Javier Bobo Pinilla
  pic: "img/team/jbobo.jpg"
  position: Postdoc researcher
  institution: Universidad de Salamanca
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: google-plus
      url: #

- name: Antonio Gonz치lez Hernandez
  pic: "img/team/agonzalez.jpg"
  position: Postdoc researcher
  institution: Universidad de Granada
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty